import { _mkText } from "./_mkText";
import { setHelpText } from "../api/help/help";

export function installGlobalHelpTexts(global: typeof globalThis) {
  for (const [value, name, link] of [
    [
      global.AggregateError,
      "AggregateError",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError`,
    ],
    [
      global.Array,
      "Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array`,
    ],
    [
      global.ArrayBuffer,
      "ArrayBuffer",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer`,
    ],
    // omitted because they're hard or impossible to get: AsyncFunction, AsyncGenerator, AsyncGeneratorFunction, AsyncIterator
    [
      global.Atomics,
      "Atomics",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics`,
    ],
    [
      global.BigInt,
      "BigInt",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt`,
    ],
    [
      global.BigInt64Array,
      "BigInt64Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array`,
    ],
    [
      global.BigUint64Array,
      "BigUint64Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array`,
    ],
    [
      global.Boolean,
      "Boolean",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean`,
    ],
    [
      global.DataView,
      "DataView",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView`,
    ],
    [
      global.Date,
      "Date",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date`,
    ],
    [
      global.decodeURI,
      "decodeURI()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI`,
    ],
    [
      global.decodeURIComponent,
      "decodeURIComponent()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent`,
    ],
    [
      global.encodeURI,
      "encodeURI()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI`,
    ],
    [
      global.encodeURIComponent,
      "encodeURIComponent()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent`,
    ],

    [
      global.Error,
      "Error",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error`,
    ],
    [
      global.escape,
      "escape()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape`,
    ],
    [
      global.eval,
      "eval()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval`,
    ],
    [
      global.EvalError,
      "EvalError",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError`,
    ],
    // FinalizationRegistry would go here, but it's not supported by QuickJS
    [
      global.Float32Array,
      "Float32Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array`,
    ],
    [
      global.Float64Array,
      "Float64Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array`,
    ],
    [
      global.Function,
      "Function",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function`,
    ],
    [
      global.globalThis,
      "globalThis",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis`,
    ],
    [
      global.Infinity,
      "Infinity",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity`,
    ],
    [
      global.Int16Array,
      "Int16Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array`,
    ],
    [
      global.Int32Array,
      "Int32Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array`,
    ],
    [
      global.Int8Array,
      "Int8Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array`,
    ],
    [
      global.InternalError,
      "InternalError",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError`,
    ],
    [
      global.isFinite,
      "isFinite()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite`,
    ],
    [
      global.isNaN,
      "isNaN()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN`,
    ],
    [
      global.JSON,
      "JSON",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON`,
    ],
    [
      global.Map,
      "Map",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map`,
    ],
    [
      global.Math,
      "Math",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math`,
    ],
    [
      global.NaN,
      "NaN",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN`,
    ],
    [
      global.Number,
      "Number",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number`,
    ],
    [
      global.Object,
      "Object",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object`,
    ],
    [
      global.parseFloat,
      "parseFloat()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat`,
    ],
    [
      global.parseInt,
      "parseInt()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt`,
    ],
    [
      global.Promise,
      "Promise",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise`,
    ],
    [
      global.Proxy,
      "Proxy",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy`,
    ],
    [
      global.RangeError,
      "RangeError",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError`,
    ],
    [
      global.ReferenceError,
      "ReferenceError",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError`,
    ],
    [
      global.Reflect,
      "Reflect",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect`,
    ],
    [
      global.RegExp,
      "RegExp",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp`,
    ],
    [
      global.Set,
      "Set",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set`,
    ],
    [
      global.SharedArrayBuffer,
      "SharedArrayBuffer",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer`,
    ],
    [
      global.String,
      "String",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String`,
    ],
    [
      global.Symbol,
      "Symbol",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol`,
    ],
    [
      global.SyntaxError,
      "SyntaxError",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError`,
    ],
    [
      global.TypeError,
      "TypeError",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError`,
    ],
    [
      global.Uint16Array,
      "Uint16Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array`,
    ],
    [
      global.Uint32Array,
      "Uint32Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array`,
    ],
    [
      global.Uint8Array,
      "Uint8Array",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array`,
    ],
    [
      global.Uint8ClampedArray,
      "Uint8ClampedArray",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray`,
    ],
    [
      global.unescape,
      "unescape()",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape`,
    ],
    [
      global.undefined,
      "undefined",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#undefined_type`,
    ],
    [
      global.URIError,
      "URIError",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError`,
    ],
    [
      global.WeakMap,
      "WeakMap",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap`,
    ],
    // WeakRef would go here, but it's not supported by QuickJS
    [
      global.WeakSet,
      "WeakSet",
      `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet`,
    ],
  ] as const) {
    setHelpText(value, _mkText(name, link));
  }
}
