const MIT = `Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.`;

const ISC = `Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.`;

export default `Licensing Information

-------------- cutils --------------

C utilities

Copyright (c) 2017 Fabrice Bellard
Copyright (c) 2018 Charlie Gordon

${MIT}

-------------- libbf --------------

Tiny arbitrary precision floating point library

Copyright (c) 2017-2021 Fabrice Bellard

${MIT}

-------------- libregexp --------------

Regular Expression Engine

Copyright (c) 2017-2018 Fabrice Bellard

${MIT}

-------------- libunicode --------------

Unicode utilities

Copyright (c) 2017-2018 Fabrice Bellard

${MIT}

-------------- list --------------

Linux klist like system

Copyright (c) 2016-2017 Fabrice Bellard

${MIT}

-------------- qjsc --------------

QuickJS command line compiler

Copyright (c) 2018-2021 Fabrice Bellard

${MIT}

-------------- quickjs (suchipi fork) --------------

QuickJS Javascript Engine

Copyright (c) 2017-2021 Fabrice Bellard
Copyright (c) 2017-2021 Charlie Gordon
Copyright (c) 2022-2022 Lily Skye

${MIT}

-------------- quickjs-libc (suchipi fork) --------------

QuickJS C library

Copyright (c) 2017-2018 Fabrice Bellard
Copyright (c) 2022-2022 Lily Skye

${MIT}

-------------- qjsbootstrap --------------

QuickJS bootstrap

Built by Lily Skye, using some code generated by qjsc.

Copyright (c) 2022-2022 Lily Skye
Copyright (c) 2017-2021 Fabrice Bellard
Copyright (c) 2017-2021 Charlie Gordon

${MIT}

-------------- quickjs repl --------------

QuickJS Read Eval Print Loop (modified)

Copyright (c) 2017-2020 Fabrice Bellard
Copyright (c) 2017-2020 Charlie Gordon
Copyright (c) 2022 Lily Skye

${MIT}

-------------- @suchipi/print --------------

The ISC License

Copyright (c) 2016-2022, John Gardner
Copyright (c) 2022 Lily Skye

${ISC}

-------------- kleur --------------

The MIT License (MIT)

Copyright (c) Luke Edwards <luke.edwards05@gmail.com> (lukeed.com)

${MIT}

-------------- minimatch --------------

The ISC License

Copyright (c) 2011-2022 Isaac Z. Schlueter and Contributors

${ISC}

-------------- brace-expansion --------------

MIT License

Copyright (c) 2013 Julian Gruber <julian@juliangruber.com>

${MIT}

-------------- balanced-match --------------

(MIT)

Copyright (c) 2013 Julian Gruber &lt;julian@juliangruber.com&gt;

${MIT}

-------------- ansi-regex --------------

MIT License

Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)

${MIT}

-------------- strip-ansi --------------

MIT License

Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)

${MIT}

-------------- @suchipi/is --------------

MIT License Copyright (c) 2022 Lily Skye

${MIT}

-------------- coffeescript --------------

Copyright (c) 2009-2018 Jeremy Ashkenas

${MIT}

-------------- lines-and-columns --------------

The MIT License (MIT)

Copyright (c) 2015 Brian Donovan

${MIT}

-------------- sucrase --------------

The MIT License (MIT)

Copyright (c) 2012-2018 various contributors (see AUTHORS)

${MIT}

---

The AUTHORS file for sucrase says:

Direct contributors to the Sucrase project:
Alan Pierce

Sucrase contains a modified fork of Babylon, which itself was forked from Acorn.
Babel and Babylon are copyright 2014-2018 Sebastian McKenzie
See https://babeljs.io/team for a list of contributors to the Babel project.

List of Acorn contributors:
Adrian Rakovsky
Alistair Braidwood
Andres Suarez
Aparajita Fishman
Arian Stolwijk
Artem Govorov
Brandon Mills
Charles Hughes
Conrad Irwin
David Bonnet
Forbes Lindesay
Gilad Peleg
impinball
Ingvar Stepanyan
Jesse McCarthy
Jiaxing Wang
Joel Kemp
Johannes Herr
Jürg Lehni
keeyipchan
Kevin Kwok
krator
Marijn Haverbeke
Martin Carlberg
Mathias Bynens
Mathieu 'p01' Henri
Max Schaefer
Max Zerzouri
Mihai Bazon
Mike Rennie
Nick Fitzgerald
Oskar Schöldström
Paul Harper
Peter Rust
PlNG
r-e-d
Rich Harris
Sebastian McKenzie
zsjforcn

-------------- clef-parse --------------

MIT License

Copyright (c) 2022 Lily Skye

${MIT}

-------------- papaparse --------------

MIT License

Copyright (c) 2015 Matthew Holt

${MIT}

-------------- yaml (npm package) --------------

The ISC License

Copyright Eemeli Aro <eemeli@gmail.com>

${ISC}

-------------- yavascript --------------

YavaScript script interpreter

MIT License

Copyright (c) 2022 Lily Skye

${MIT}
`;
